version: '3.8'

services:
  italy-trip-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: italy-trip-api
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload